### ISSUE TITLE
Wrong resources loaded when using turbopack

### ISSUE THREAD

**Issue by guillermopd** [i18next/i18next-resources-to-backend#10]
## 🐛 Bug Report

When using dev mode and turbopack, the loaded resources are wrong.

## To Reproduce

Clone the example repo: https://github.com/i18next/next-app-dir-i18next-example-ts, add --turbo to next dev script in package.json, optionally enable i18next debug in app/i18n/settings.ts

If debug is enabled, the output shows the same resource for different languages is loaded:

```
i18next::backendConnector: loaded namespace footer for language it {
  'back-to-home': 'Zurück zur Hauptseite',
  counter_one: 'eines ausgewählt',
  counter_other: '{{count}} ausgewählt',
  counter_zero: 'keines ausgewählt',
  h1: 'Eine client Seite, um das client-seitige i18n zu demonstrieren',
  title: 'Client Seite',
  'to-second-client-page': 'zur zweiten client Seite'
}
i18next::backendConnector: loaded namespace footer for language en {
  'back-to-home': 'Zurück zur Hauptseite',
  counter_one: 'eines ausgewählt',
  counter_other: '{{count}} ausgewählt',
  counter_zero: 'keines ausgewählt',
  h1: 'Eine client Seite, um das client-seitige i18n zu demonstrieren',
  title: 'Client Seite',
  'to-second-client-page': 'zur zweiten client Seite'
}
```

``
## Expected behavior

Either warn about this problem in the docs or review the resource loading. It seems like a cache problem but I can't validate that.

## Your Environment

- *runtime version*: node v20
- *i18next version*: 23.8.2
- *os*: Linux

**Comment by adrai** [comment]
Please open an issue for Next.js or Turbopack... i18next-resources-to-backend is only doing a normal import... https://github.com/i18next/next-app-dir-i18next-example-ts/blob/main/app/i18n/index.ts#L12

**Comment by adrai** [comment]
maybe related: https://github.com/vercel/next.js/issues/56531
