### ISSUE TITLE
Dynamic lazy loading tries to load default namespace even with defaultNS set to false

### ISSUE THREAD

**Issue by jasperfirecai2** [i18next/i18next-resources-to-backend#13]
## 🐛 Bug Report

When setting up the code example for resourcesToBackend, on init it will try to load `./locales/{language}/translation.json` (the default namespace). However, when defaultNS is set to false or empty array, [this fallback behaviour is not expected](https://www.i18next.com/overview/configuration-options#languages-namespaces-resources). 

## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).

```js
import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import resourcesToBackend from "i18next-resources-to-backend";

export const LANGUAGES = ["nl-NL", "en-GB"]; //just as an example of my env

i18n
  .use(initReactI18next)
  .use(resourcesToBackend((language, namespace) => import(`./locales/${language}/${namespace}.json`)))
  .on('failedLoading', (lng, ns, msg) => console.error(msg))
  .init({
    defaultNS: false, // or [], or "foobar"
    fallbackLng: "en-GB",
    supportedLngs: LANGUAGES,
  });

export default i18n;

```

## Expected behavior

I expected the dynamic lazy loading to only load when a namespace is requested in a `useTranslation()` hook. Instead it does that, but *also* loads the 'default fallback' namespace (and fails because it doesn't exist). Had to write a manual workaround to stop this behaviour.

```js
.use(resourcesToBackend((language, namespace) => {
    if (namespace === "translation") return;
    return import(`./locales/${language}/${namespace}.json`);
  }))
```

## Your Environment

- *runtime version*: node v20
- *i18next version*: 23.16.8
- *i18next-resources-to-backend version*: 1.2.1
- *react-i18next version*: 15.1.1
- *os*: WSL 2 on Windows 11
- vite server with react-i18next, issue occurs on first init in index.jsx. app does not crash, just logs error

**Comment by adrai** [comment]
That's not related to i18next-resources-to-backend, but to the default behaviour in i18next.
And it behaves exactly how it should: https://www.i18next.com/overview/configuration-options#languages-namespaces-resources
<img width="842" alt="image" src="https://github.com/user-attachments/assets/4a73b969-3929-4e1a-8ccc-c04de2e7b895">
What you want is setting the ns option to an empty array, like this:

```js
import i18next from "i18next";
import resourcesToBackend from "i18next-resources-to-backend";

export const LANGUAGES = ["nl-NL", "en-GB"]; //just as an example of my env

i18next
  .use(resourcesToBackend((language, namespace) => {
    console.log(`loading ${language}-${namespace}...`)
    return {
      exampleKEy: `loaded-${language}-${namespace}`
    }
  }))
  .on('failedLoading', (lng, ns, msg) => console.error(msg))
  .init({
    ns: [],
    defaultNS: 'translation',
    fallbackLng: "en-GB",
    supportedLngs: LANGUAGES,
  });

```

**Comment by jasperfirecai2** [comment]
You're right. i'm sorry for misreading the docs. thank you for the quick answer and solution
