### ISSUE TITLE
Could not find a declaration file for module 'i18next-resources-to-backend'

### ISSUE THREAD

**Issue by kim-nguyenkhn** [i18next/i18next-resources-to-backend#5]
## 🐛 Bug Report

```shell
Could not find a declaration file for module 'i18next-resources-to-backend'. '/Users/kim.nguyen/workspace/embedded-javascript-sdk/node_modules/.pnpm/i18next-resources-to-backend@1.1.2/node_modules/i18next-resources-to-backend/dist/esm/index.js' implicitly has an 'any' type.
  There are types at '/Users/kim.nguyen/workspace/embedded-javascript-sdk/packages/embedded-ui/node_modules/i18next-resources-to-backend/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'i18next-resources-to-backend' library may need to update its package.json or typings.ts(7016)
```

## To Reproduce

```js
import resourcesToBackend from 'i18next-resources-to-backend';

const i18nextOptions = {
  debug: true,
  fallbackLng: 'en',
};

i18next
    .use(
      resourcesToBackend(
        (language: string, namespace: string) => import(`./${language}/${namespace}.json`),
      ),
    )
    .init(i18nextOptions);
```

## Expected behavior

No error.

## Your Environment

- *runtime version*: node v16
- *i18next version*: 22.4.11
- *os*: Mac

**Comment by kim-nguyenkhn** [comment]
When I added "types" to the default exports of this package, it worked:

```json
  "exports": {
    ".": {
      "require": "./dist/cjs/index.js",
      "default": "./dist/esm/index.js",
      "types": "./index.d.ts"
    }
  },
```

**Comment by adrai** [comment]
Please provide a codesandbox example or a reproducible repository.

**Comment by adrai** [comment]
Seems to work in tests: https://github.com/i18next/i18next-resources-to-backend/blob/main/test/types/i18next-resources-to-backend.test-d.ts

**Comment by marklai1998** [comment]
@adrai  I got this error with the new Typescript V5 with the new `moduleResolution=bundler`
it follows the hybrid module resolution of your installed bundler, Vite in my case
ref: https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler

**Comment by adrai** [comment]
@pedrodurek is this a real issue?

**Comment by caguado** [comment]
Indeed it is an issue as choosing a different module resolution trips typing resolution.

https://github.com/microsoft/TypeScript/issues/51996#issuecomment-1372637079

**Comment by adrai** [comment]
@caguado if you know of a nice way how to address this, I'm happy to hear it.

**Comment by adrai** [comment]
try with v1.1.4
