### ISSUE TITLE
i18n.init promise not resolving

### ISSUE THREAD

**Issue by jessypouliot98** [i18next/i18next-resources-to-backend#6]
## 🐛 Bug Report

Edit: The issue came back, maybe this should be on stand by while I look into it again.. 😭

I believe this package doesn't work well with latest version or i18next

For context, I just recreated my entire monorepo to fix some issues I had with react-native and in this new repo I had issues with loading my translations. I see in network tab that they are fetched correctly but i18n.init is never resolved (no promise error either). After a couple days of trying to debug I decided to just copy and paste my dependency versions from last repo and it fixed my issue. (I don't believe it's broken from 1.1.2 after my quick look in your commit history, but I think it might be how this connected to newer i18next versions)

left = current up to date
right = old repo working versions
![Screenshot 2023-03-19 at 11 01 58 PM](https://user-images.githubusercontent.com/35693647/226237400-f1dbc1e4-f6f5-4597-95c0-4f8753834ae6.png)

## To Reproduce

This is my code I used, it's not very copy-pastable, but I've added some comments to help with understanding

```typescript
const BackendResource = resourcesToBackend(async (...args) => {
  const [lang, ns] = args as [LangType, NamespaceType];
  const now = Date.now();
  const appVersion = Config.version;
  const storageTranslationKey = `translation.${lang}.${ns}` as const;

  // When in dev mode, ignore cache : When not, use local cache and validate if it should be used or refetched
  const localTranslation = __DEV__ ? null : await Storage.get(storageTranslationKey);
  if (localTranslation) {
    if (
      isSameWeek(now, localTranslation.cacheDate) &&
      localTranslation.appVersion === appVersion
    ) {
      return localTranslation;
    }
  }

  // Make sure Firebase config was loaded to get appropriate "LOCALE_URL"
  await RemoteConfig.setup().catch((err) => console.error(err));

  try {
    const serverTranslation = await fetch(urlWithQuery(`${RemoteConfig.getUrl('LOCALE_URL')}/${lang}/${ns}.json`, { v: appVersion }))
      .then((res) => res.json());

   // Cache translation localy
    await Storage.set(storageTranslationKey, {
      cacheDate: now,
      appVersion,
      translations: serverTranslation,
    });

   // Return cache or fetched translations
    return serverTranslation;
  } catch (err) {
    console.error(err)
    // Return empty object and assume no key was ever defined
    return {};
  }
});
```

```typescript
export function useI18nSetup() {
  const [i18nInitialized, setI18nInitialized] = useState(false);

  useEffect(() => {
    // Force non-blocking after 5seconds (give some time to serverless cold-start)
    const timeout = setTimeout(() => setI18nInitialized(true), 5000);
    i18next
      .use(initReactI18next)
      .use(BackendResource)
      .init({
        react: {
          useSuspense: false, // Prevents synchronous issue
        },
        interpolation: {
          escapeValue: false, // not needed for react as it escapes by default
        },
        load: 'languageOnly',
        supportedLngs: SupportedLanguages,
        lng: FallbackLanguage, // TODO -- Auto detect
        fallbackLng: FallbackLanguage,
        ns: Namespaces,
      })
      .then(() => {
        console.log('i18n works');
        setI18nInitialized(true);
      })
      .catch((err) => {
        console.log('i18n err')
        setI18nInitialized(true);
      })
      .finally(() => {
        clearTimeout(timeout);
      });
  }, []);

  return i18nInitialized;
}
```

## Expected behavior

I expect `i18n.init` to resolve as it should / usually did

## Your Environment

- *runtime version*: v18.12.1
- *i18next version*: 22.4.12
- *os*: Mac

**Comment by adrai** [comment]
Instead of `async (...args) => {` try with `async (lng, ns) => {`

**Comment by jessypouliot98** [comment]
> Instead of `async (...args) => {` try with `async (lng, ns) => {`

I had already tried it, but anyway I can confirm that method is not the issue because the code is always running as expected without any exceptions 

```typescript
try {
    const serverTranslation = await fetch(urlWithQuery(`${RemoteConfig.getUrl('LOCALE_URL')}/${lang}/${ns}.json`, { v: appVersion }))
      .then((res) => res.json());

   // Cache translation localy
    await Storage.set(storageTranslationKey, {
      cacheDate: now,
      appVersion,
      translations: serverTranslation,
    });

    console.log({ lang, ns, serverTranslation }); // This always logs as expected + network tab shows me all the fetch request responsing as expected
   // Return cache or fetched translations
    return serverTranslation;
  } catch (err) {
    console.error(err)
    // Return empty object and assume no key was ever defined
    return {};
  }
```

I'm very confused as to why this is an issue. I'll be investigating more monorepo specific reasons this could be running incorrectly tonight.

I'm unsure if my issue is from this package, I was able to run with static resources without this package setup, so it does seem like it.

**Comment by adrai** [comment]
try with v1.1.3...
if it works, it was the function signature...

**Comment by jessypouliot98** [comment]
Just got back on my project and yeah you were right about the spread operator.. 😅

Thank you very much for the fix and help ! 🙏
